services:
  pe_app:
    build: .
    container_name: pe_app
    restart: unless-stopped
    env_file: .env
    volumes:
      - pe_data:/app/prisma
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pe_app.rule=Host(`app.proexergy.com`)"
      - "traefik.http.routers.pe_app.entrypoints=websecure"
      - "traefik.http.routers.pe_app.tls.certresolver=letsencrypt"
      - "traefik.http.services.pe_app.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  pe_data:
